/**
 * The Python emitter: model in, pydantic source out.
 *
 * Python idiom only — the model already resolved everything. Design mirrors
 * the handwritten SDK where the two agree (snake_case fields behind to_camel
 * aliases, EventType as a str Enum, Literal discriminators, Annotated
 * discriminated unions) and follows the schema where they differ: required
 * fields have no defaults, explicit null is rejected wherever the schema has
 * no null, and — the reason this target exists — the generated base model
 * omits valueless fields when serializing, by default, instead of each model
 * remembering to.
 *
 * If a field's meaning ever appears in this file, it has escaped the schema.
 */

import type {
  Definition,
  Field,
  ObjectDefinition,
  ProtocolModel,
  TypeExpr,
} from "./ir";

/** The one enum emitted as a Python Enum rather than a Literal alias. */
const PY_ENUM = "EventType";

const PYTHON_KEYWORDS = new Set([
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
]);

function banner(model: ProtocolModel): string {
  return [
    "# @generated by spec/generator — DO NOT EDIT.",
    `# Source: ${model.schemaId}`,
    "# Regenerate: pnpm --filter @ag-ui/spec generate",
    "",
  ].join("\n");
}

/** camelCase → snake_case, the exact inverse of pydantic's to_camel. */
function snakeCase(name: string): string {
  return name.replace(/([A-Z])/g, "_$1").toLowerCase();
}

/** The Python attribute for a wire field, dodging keywords with a suffix. */
function pythonName(wireName: string): string {
  const snake = snakeCase(wireName);
  return PYTHON_KEYWORDS.has(snake) ? `${snake}_` : snake;
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Wraps a description into an indented docstring. */
function docstring(description: string, indent: string): string {
  const width = 76 - indent.length;
  const words = description.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (candidate.length > width && current !== "") {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current !== "") lines.push(current);
  if (lines.length === 1 && !lines[0].includes('"""')) {
    return `${indent}"""${lines[0]}"""`;
  }
  return [
    `${indent}"""`,
    ...lines.map((line) => `${indent}${line}`),
    `${indent}"""`,
  ].join("\n");
}

/** Renders a TypeExpr as a Python annotation. */
function pyType(type: TypeExpr): string {
  switch (type.kind) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "boolean":
      return "bool";
    case "literal":
      return type.enumRef === PY_ENUM
        ? `Literal[${PY_ENUM}.${type.value}]`
        : `Literal["${escapeString(type.value)}"]`;
    case "any":
      return "Any";
    case "openMap":
      return "Dict[str, Any]";
    case "stringEnum":
      return `Literal[${type.values
        .map((value) => `"${escapeString(value)}"`)
        .join(", ")}]`;
    case "ref":
      // Definitions are emitted in dependency order, so the target is always
      // already defined — no forward references, no rebuild step.
      return type.name;
    case "array":
      return `List[${pyType(type.items)}]`;
    case "union":
      return `Union[${type.members.map(pyType).join(", ")}]`;
  }
}

/** The Field(...) arguments a field's constraints and wiring need. */
function fieldArguments(field: Field, pyName: string): string[] {
  const args: string[] = [];
  if (!field.required) args.push("default=None");
  // The alias generator inverts snake_case back to the wire name; a keyword
  // dodge (from_) needs the alias spelled out.
  if (pyName !== snakeCase(field.name)) {
    args.push(`alias="${escapeString(field.name)}"`);
  }
  if (field.type.kind === "integer") {
    if (field.type.minimum !== undefined) args.push(`ge=${field.type.minimum}`);
    if (field.type.maximum !== undefined) args.push(`le=${field.type.maximum}`);
  }
  if (field.type.kind === "string" && field.type.pattern !== undefined) {
    args.push(`pattern=r"${field.type.pattern.replace(/"/g, '\\"')}"`);
  }
  if (field.type.kind === "array" && field.type.minItems !== undefined) {
    args.push(`min_length=${field.type.minItems}`);
  }
  return args;
}

function emitObject(definition: ObjectDefinition): string {
  // Real inheritance, because Python consumers isinstance-check against the
  // bases: events subclass BaseEvent and the name-bearing messages subclass
  // BaseMessage, each redeclaring its flattened fields (a redeclaration
  // narrows in place, pydantic-style). Attributable contributes fields only.
  const base = definition.composedMixins.includes("BaseEvent")
    ? "BaseEvent"
    : definition.composedMixins.includes("BaseMessage")
      ? "BaseMessage"
      : "GeneratedBaseModel";
  const lines: string[] = [`class ${definition.name}(${base}):`];
  lines.push(docstring(definition.description, "    "));
  lines.push("");
  // A field that dodges a Python keyword (from_) would leak its dodge into
  // plain dumps, handing "from_" to code that feeds a JSON Patch library.
  // Serialising by alias restores the RFC member name; it is safe here
  // because every other field's alias differs from its name only by casing
  // that these one-word fields do not have.
  if (definition.fields.some((field) => pythonName(field.name).endsWith("_"))) {
    lines.push('    model_config = ConfigDict(serialize_by_alias=True)');
    lines.push("");
  }

  for (const field of definition.fields) {
    const pyName = pythonName(field.name);
    const annotation = field.required
      ? pyType(field.type)
      : `Optional[${pyType(field.type)}]`;
    const args = fieldArguments(field, pyName);
    const description =
      field.type.kind === "array" && field.type.itemsDescription !== undefined
        ? `${field.description} Each item: ${field.type.itemsDescription}`
        : field.description;
    // A single-value literal is a const, not a schema default: the only
    // possible value is supplied so constructors never have to spell the
    // discriminator, exactly as the hand-written models always worked.
    // (Schema DEFAULTS stay documentation and are never materialised.)
    const constValue =
      field.required && field.type.kind === "literal"
        ? field.type.enumRef === PY_ENUM
          ? `${PY_ENUM}.${field.type.value}`
          : `"${escapeString(field.type.value)}"`
        : undefined;
    const value =
      args.length > 0
        ? ` = Field(${args.join(", ")})`
        : constValue !== undefined
          ? ` = ${constValue}`
          : "";
    lines.push(`    ${pyName}: ${annotation}${value}`);
    lines.push(docstring(description, "    "));
  }

  return lines.join("\n");
}

/** Whether a ref field ultimately names an any alias (resolved by caller). */
let anyAliasNames = new Set<string>();
function refIsAny(type: TypeExpr): boolean {
  return type.kind === "ref" && anyAliasNames.has(type.name);
}

/** The Field(...) arguments a bare type's constraints need, field-agnostic. */
function constraintArguments(type: TypeExpr): string[] {
  const args: string[] = [];
  if (type.kind === "integer") {
    if (type.minimum !== undefined) args.push(`ge=${type.minimum}`);
    if (type.maximum !== undefined) args.push(`le=${type.maximum}`);
  }
  if (type.kind === "string" && type.pattern !== undefined) {
    args.push(`pattern=r"${type.pattern.replace(/"/g, '\\"')}"`);
  }
  if (type.kind === "array" && type.minItems !== undefined) {
    args.push(`min_length=${type.minItems}`);
  }
  return args;
}

/** An alias's annotation, keeping constraints a bare name would drop. */
function aliasAnnotation(type: TypeExpr): string {
  const args = constraintArguments(type);
  return args.length > 0
    ? `Annotated[${pyType(type)}, Field(${args.join(", ")})]`
    : pyType(type);
}

function emitDefinition(definition: Definition): string {
  switch (definition.kind) {
    case "object":
      return emitObject(definition);
    case "union": {
      const union = `Union[${definition.members.join(", ")}]`;
      const annotated =
        definition.discriminator !== undefined
          ? `Annotated[\n    ${union},\n    Field(discriminator="${definition.discriminator}"),\n]`
          : union;
      return [
        `${definition.name} = ${annotated}`,
        docstring(definition.description, ""),
      ].join("\n");
    }
    case "enum": {
      if (definition.name === PY_ENUM) {
        const members = definition.values
          .map((value) => `    ${value} = "${value}"`)
          .join("\n");
        return [
          `class ${definition.name}(str, Enum):`,
          docstring(definition.description, "    "),
          "",
          members,
        ].join("\n");
      }
      const values = definition.values
        .map((value) => `"${escapeString(value)}"`)
        .join(", ");
      return [
        `${definition.name} = Literal[${values}]`,
        docstring(definition.description, ""),
      ].join("\n");
    }
    case "alias":
      return [
        `${definition.name} = ${aliasAnnotation(definition.type)}`,
        docstring(definition.description, ""),
      ].join("\n");
  }
}

const OMITTABLE_KEYS_CACHE_ATTR = "_agui_omittable_keys";

const BASE_MODEL = `_OMITTABLE_KEYS_CACHE_ATTR = "${OMITTABLE_KEYS_CACHE_ATTR}"


class GeneratedBaseModel(BaseModel):
    """
    The generated base model — the public SDK's ergonomics, not a wire
    artifact. Wire names are camelCase behind snake_case attributes, and both
    spellings populate a model, because Python callers construct with the
    attribute names. Unknown fields are kept, not dropped, so a boundary that
    wants to warn about them can still see them and a re-serialising
    intermediary does not lose them. Coercion is pydantic's default: the
    strict contract is the specification's validation corpus, not this class.

    Serialization omits every optional field that has no value instead of
    writing it out as JSON \`\`null\`\`. Pydantic's default is to include it, which
    made this SDK the only AG-UI producer that put \`\`null\`\` on the wire where
    TypeScript simply left the key out. Omission is applied here, in the base
    model, so it holds on every serialization path (\`\`model_dump\`\`,
    \`\`model_dump_json\`\`, nesting inside another model, and any
    \`\`TypeAdapter\`\`) rather than depending on each call site remembering
    \`\`exclude_none=True\`\`.

    "Has no value" means a field that is declared optional *and* defaults to
    \`\`None\`\` — exactly the set the contract lets a producer leave out. Nulls
    that carry meaning are untouched: a required field (CUSTOM.value, say), a
    \`\`None\`\` inside a \`\`dict\`\`/\`\`list\`\` value, and any extra field all
    serialize as \`\`null\`\`.
    """

    model_config = ConfigDict(
        extra="allow",
        alias_generator=to_camel,
        populate_by_name=True,
    )

    @classmethod
    def _omittable_keys(cls) -> FrozenSet[str]:
        """
        The serialized keys that may be dropped when their value is \`\`None\`\`.

        Both the field name and its alias are included, because the caller
        chooses between them with \`\`by_alias\`\`. Cached per class in the class's
        own \`\`__dict__\`\` so a subclass never inherits its parent's answer.
        """
        cached = cls.__dict__.get(_OMITTABLE_KEYS_CACHE_ATTR)
        if cached is None:
            keys = set()
            for name, field in cls.model_fields.items():
                if not field.is_required() and field.default is None:
                    keys.add(name)
                    if field.alias is not None:
                        keys.add(field.alias)
                    if field.serialization_alias is not None:
                        keys.add(field.serialization_alias)
            cached = frozenset(keys)
            setattr(cls, _OMITTABLE_KEYS_CACHE_ATTR, cached)
        return cached

    @model_serializer(mode="wrap")
    def _omit_fields_without_value(self, handler: SerializerFunctionWrapHandler):
        # Deliberately unannotated return: annotating it (\`\`Dict[str, Any]\`\`, say)
        # makes Pydantic replace the model's serialization JSON schema with a bare
        # \`\`{"type": "object"}\`\`. Left off, the handler's own schema is kept.
        serialized = handler(self)
        omittable = type(self)._omittable_keys()
        return {
            key: value
            for key, value in serialized.items()
            if value is not None or key not in omittable
        }`;

export function emitModels(model: ProtocolModel): string {
  anyAliasNames = new Set<string>();
  let grew = true;
  while (grew) {
    grew = false;
    for (const definition of model.definitions) {
      if (definition.kind !== "alias" || anyAliasNames.has(definition.name))
        continue;
      const target = definition.type;
      if (
        target.kind === "any" ||
        (target.kind === "ref" && anyAliasNames.has(target.name))
      ) {
        anyAliasNames.add(definition.name);
        grew = true;
      }
    }
  }

  const imports = [
    "from enum import Enum",
    "from typing import Annotated, Any, Dict, FrozenSet, List, Literal, Optional, Union",
    "",
    "from pydantic import BaseModel, ConfigDict, Field, model_serializer",
    "from pydantic.alias_generators import to_camel",
    "from pydantic.functional_serializers import SerializerFunctionWrapHandler",
  ].join("\n");

  // The mixin shapes become real classes (BaseEvent, BaseMessage,
  // Attributable): the hand-written SDK's public hierarchy, which consumers
  // isinstance-check against. Inserted immediately before the first
  // definition that inherits one, after the aliases and enums they depend on.
  const mixinClasses = model.mixinShapes.map((shape) =>
    emitObject({ ...shape, composedMixins: [] }),
  );
  const emitted = model.definitions.map(emitDefinition);
  const firstInheritor = model.definitions.findIndex(
    (definition) =>
      definition.kind === "object" && definition.composedMixins.length > 0,
  );
  const insertAt = firstInheritor === -1 ? emitted.length : firstInheritor;
  emitted.splice(insertAt, 0, ...mixinClasses);

  return [banner(model), imports, BASE_MODEL, ...emitted, ""].join("\n\n\n");
}

export function emitPythonVersion(model: ProtocolModel): string {
  return [
    banner(model),
    [
      `PROTOCOL_VERSION = "${escapeString(model.version)}"`,
      docstring(
        `The protocol version this code was generated from: the version segment of the schema's $id (${model.schemaId}). Never typed by a human.`,
        "",
      ),
    ].join("\n"),
    "",
  ].join("\n\n");
}

export function emitPythonInit(model: ProtocolModel): string {
  return [
    banner(model),
    docstring(
      "The generated protocol models: the internal source ag_ui.core re-exports. Regenerate with `pnpm --filter @ag-ui/spec generate`; the shape follows the schema.",
      "",
    ),
    "",
  ].join("\n");
}

export interface GeneratedPythonFile {
  name: string;
  content: string;
}

export function emitPython(model: ProtocolModel): GeneratedPythonFile[] {
  return [
    { name: "__init__.py", content: emitPythonInit(model) },
    { name: "models.py", content: emitModels(model) },
    { name: "version.py", content: emitPythonVersion(model) },
  ];
}
