import { existsSync, readFileSync, readdirSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildModel } from "../generator/ir";
import { buildWireModel, emitProtoFiles } from "../generator/protobuf";
import { FREEZE_PATH } from "../generator/generate";
import {
  DOCS_SPEC_OUTPUT_DIR,
  DOTNET_MODELS_OUTPUT_DIR,
  DOTNET_OUTPUT_DIR,
  generateFiles,
  PROTO_OUTPUT_DIR,
  PY_OUTPUT_DIR,
  SCHEMA_PATH,
  TS_OUTPUT_DIR,
} from "../generator/generate";
import { schema } from "./validator";
import * as generatedSchemas from "../../sdks/typescript/packages/core/src/generated/schemas";

const files = await generateFiles();
const PUBLISHED_SCHEMA_PATH = join(DOCS_SPEC_OUTPUT_DIR, "schema.json");
const model = buildModel(schema);

describe("the generator", () => {
  it("is deterministic: generating twice produces identical output", async () => {
    expect(await generateFiles()).toEqual(files);
  });

  it("matches the committed output, byte for byte", () => {
    // This is the CI gate: a schema or generator change without a matching
    // regeneration fails here, and so does a hand edit to a generated file.
    for (const dir of [
      TS_OUTPUT_DIR,
      PY_OUTPUT_DIR,
      PROTO_OUTPUT_DIR,
      DOTNET_OUTPUT_DIR,
      DOTNET_MODELS_OUTPUT_DIR,
      DOCS_SPEC_OUTPUT_DIR,
    ]) {
      const committed = readdirSync(dir)
        .filter((name) => name !== "__pycache__")
        // The published schema shares its folder with the specification pages,
        // by design: /spec/draft/schema.json is a file and /spec/draft/lifecycle
        // is a page. The pages are hand-written and not the generator's
        // business — except schema.mdx, the generated reference — so the
        // "nothing here the generator did not emit" rule applies to the
        // machine-readable half plus that one page.
        .filter(
          (name) =>
            dir !== DOCS_SPEC_OUTPUT_DIR ||
            name.endsWith(".json") ||
            name === "schema.mdx",
        )
        .sort();
      const emitted = files
        .filter((file) => dirname(file.path) === dir)
        .map((file) => basename(file.path))
        .sort();
      expect(committed, `${dir} has files the generator did not emit`).toEqual(
        emitted,
      );
    }
    for (const file of files) {
      expect(
        readFileSync(file.path, "utf8"),
        `${file.path} is stale — run: pnpm --filter @ag-ui/spec generate`,
      ).toBe(file.content);
    }
  });

  it("emits exactly 31 events", () => {
    const eventType = model.definitions.find(
      (definition) => definition.name === "EventType",
    );
    const eventUnion = model.definitions.find(
      (definition) => definition.name === "Event",
    );
    expect(eventType?.kind).toBe("enum");
    expect(eventUnion?.kind).toBe("union");
    if (eventType?.kind !== "enum" || eventUnion?.kind !== "union") return;
    expect(eventType.values).toHaveLength(31);
    expect(eventUnion.members).toHaveLength(31);
  });

  it("derives the version constant from the schema's own address", () => {
    // The constant is never typed by a human: it is the version segment of the
    // $id, which is also the directory the schema lives in.
    const directory = basename(dirname(SCHEMA_PATH));
    expect(model.version).toBe(directory);
    for (const [path, declaration] of [
      [join(TS_OUTPUT_DIR, "version.ts"), "const PROTOCOL_VERSION ="],
      [join(PY_OUTPUT_DIR, "version.py"), "PROTOCOL_VERSION ="],
    ]) {
      const version = files.find((file) => file.path === path);
      expect(version, path).toBeDefined();
      expect(version?.content).toContain(
        `${declaration} ${JSON.stringify(model.version)}`,
      );
    }
  });

  it("marks every emitted file as generated", () => {
    for (const file of files) {
      // The published schema is the schema: the same bytes served at the
      // address its own $id names. JSON has no comment syntax to carry a
      // banner, and a banner would make the served file differ from the file
      // it is supposed to be. Its own gate is the byte comparison below.
      if (file.path === PUBLISHED_SCHEMA_PATH) continue;
      const comment =
        file.path.endsWith(".py") || file.path.endsWith(".txt") ? "#" : "//";
      // C# files lead with the <auto-generated /> marker Roslyn analyzers
      // recognise; the @generated banner is the line after it. MDX pages must
      // lead with their frontmatter, so the banner is an MDX comment directly
      // after it.
      const banner = file.path.endsWith(".cs")
        ? `// <auto-generated />\n${comment} @generated`
        : file.path.endsWith(".mdx")
          ? "---\n"
          : `${comment} @generated`;
      if (file.path.endsWith(".mdx")) {
        expect(
          file.content,
          `${file.path} has no @generated banner after its frontmatter`,
        ).toContain("{/* @generated");
      }
      expect(
        file.content.startsWith(banner),
        `${file.path} has no @generated banner`,
      ).toBe(true);
      expect(file.content).toContain("DO NOT EDIT");
      expect(file.content).toContain(model.schemaId);
    }
  });

  it("accounts for every schema definition: emitted, or flattened as a mixin", () => {
    // A definition the reader silently dropped would vanish from every
    // generated SDK. Emitted definitions and mixins must partition $defs.
    const defs = Object.keys(schema.$defs as Record<string, unknown>).sort();
    const emitted = model.definitions.map((definition) => definition.name);
    const covered = [...emitted, ...model.mixins].sort();
    expect(covered).toEqual(defs);
    expect(model.mixins).toEqual(["Attributable", "BaseEvent", "BaseMessage"]);
  });

  it("keeps the generated Python as the only protocol source in ag_ui", () => {
    // The inverse gate since PNI-213 (mirroring the TypeScript one below):
    // the generated models are the internal source, the package must consume
    // them, and hand-written protocol declarations must not return. Scanned
    // by shape: a pydantic model declaring protocol semantics outside the
    // generated directory would subclass BaseModel or declare wire fields.
    const packageDir = join(PY_OUTPUT_DIR, "..", "core");
    const events = readFileSync(join(packageDir, "events.py"), "utf8");
    const types = readFileSync(join(packageDir, "types.py"), "utf8");
    expect(events).toContain("from ag_ui._generated.models import");
    expect(types).toContain("from ag_ui._generated.models import");
    // No hand-written module may re-declare the protocol surface: an
    // EventType enum or a pydantic event class outside generated/ is a
    // duplicate. (capabilities.py is not protocol and may keep its models.)
    for (const [name, content] of [
      ["events.py", events],
      ["types.py", types],
    ] as const) {
      expect(
        /class\s+\w+\((BaseModel|ConfiguredBaseModel|MetadataMixin|BaseEvent|BaseMessage)\)/.test(
          content,
        ),
        `${name} re-declares protocol models that belong to the generated source`,
      ).toBe(false);
      expect(
        /class\s+EventType\b/.test(content),
        `${name} re-declares EventType`,
      ).toBe(false);
    }
  });

  it("keeps the generated TypeScript as the only protocol source in core", () => {
    // The inverse gate since PNI-212: the generated directory is the internal
    // source, the package entry must actually consume it, and the old
    // hand-written duplicate homes must not quietly return.
    const srcDir = join(TS_OUTPUT_DIR, "..");
    const index = readFileSync(join(srcDir, "index.ts"), "utf8");
    expect(index).toContain('"./generated/types"');
    expect(index).toContain('"./generated/schemas"');
    for (const retired of ["events.ts", "types.ts"]) {
      expect(
        existsSync(join(srcDir, retired)),
        `${retired} was retired by PNI-212; protocol semantics live in generated/`,
      ).toBe(false);
    }
    // No hand-written module may re-declare the protocol surface: looseObject
    // is the generated validators' signature shape, and an EventType enum
    // outside generated/ is a duplicate constant table.
    for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
      const content = readFileSync(join(srcDir, entry.name), "utf8");
      expect(
        /z\.looseObject|enum EventType/.test(content),
        `${entry.name} re-declares protocol semantics that belong to generated/`,
      ).toBe(false);
    }
  });

  it("mentions the generated directory nowhere in the package manifest", () => {
    // The scan above proves nothing reachable from the entries touches the
    // generated directories; this closes the other door — a package.json
    // entry (exports, files, main) pointing into generated/ directly.
    const manifest = readFileSync(
      join(TS_OUTPUT_DIR, "..", "..", "package.json"),
      "utf8",
    );
    expect(manifest).not.toContain("generated");
  });
});

describe("the wire freeze machinery", () => {
  const committedFreeze = readFileSync(FREEZE_PATH, "utf8");

  it("turns an orphaned slot into a reserved number", () => {
    // A freeze entry whose schema field is gone must become a protobuf
    // reserved statement — in messages and in enums alike.
    const doctored =
      committedFreeze +
      "Interrupt.legacy_field = 9\n" +
      "JsonPatchOperationType.LEGACY = 6\n";
    const wire = buildWireModel(model, doctored);
    const byName = Object.fromEntries(
      emitProtoFiles(wire).map((file) => [file.name, file.content]),
    );
    expect(byName["types.proto"]).toContain("reserved 9;");
    expect(byName["patch.proto"]).toContain("reserved 6;");
  });

  it("refuses to reserve an orphaned zero enum value", () => {
    // proto3 requires the first enum value to be zero; retiring it is a wire
    // design decision, not something to generate blind.
    const doctored = committedFreeze
      .replace(
        "JsonPatchOperationType.ADD = 0",
        "JsonPatchOperationType.ADD_OLD = 0",
      )
      .replace("JsonPatchOperation.op = 1", "JsonPatchOperation.op = 1");
    const wire = buildWireModel(model, doctored);
    expect(() => emitProtoFiles(wire)).toThrow(/zero value was removed/);
  });
});

describe("the generated zod schemas against the fixture corpus", () => {
  // The fixtures are the behavioural contract, so the generated validators
  // must agree with them wherever the semantics are meant to coincide. The one
  // deliberate divergence is closure: the spec is strict and the generated zod
  // is loose (unknown keys survive for the strip-and-warn middleware), so a
  // fixture rejected only by unevaluatedProperties is expected to parse.
  const FIXTURES_DIR = join(dirname(SCHEMA_PATH), "fixtures");
  const schemas = generatedSchemas as unknown as Record<
    string,
    { safeParse: (value: unknown) => { success: boolean } }
  >;

  const collect = (
    kind: "valid" | "invalid",
  ): Array<[string, string, string]> => {
    const entries: Array<[string, string, string]> = [];
    for (const anchor of readdirSync(FIXTURES_DIR).sort()) {
      const dir = join(FIXTURES_DIR, anchor, kind);
      if (!existsSync(dir)) continue;
      for (const file of readdirSync(dir).sort()) {
        if (!file.endsWith(".json") || file.endsWith(".expect.json")) continue;
        entries.push([`${anchor}/${kind}/${file}`, anchor, join(dir, file)]);
      }
    }
    return entries;
  };

  it.each(collect("valid"))("%s parses", (_name, anchor, path) => {
    const validator = schemas[`${anchor}Schema`];
    expect(validator, `no generated schema for ${anchor}`).toBeDefined();
    const document = JSON.parse(readFileSync(path, "utf8")) as unknown;
    expect(validator.safeParse(document).success).toBe(true);
  });

  const rejected = collect("invalid").filter(([, , path]) => {
    const expectation = JSON.parse(
      readFileSync(path.replace(/\.json$/, ".expect.json"), "utf8"),
    ) as { keyword: string };
    return expectation.keyword !== "unevaluatedProperties";
  });

  it.each(rejected)("%s fails to parse", (_name, anchor, path) => {
    const validator = schemas[`${anchor}Schema`];
    expect(validator, `no generated schema for ${anchor}`).toBeDefined();
    const document = JSON.parse(readFileSync(path, "utf8")) as unknown;
    expect(validator.safeParse(document).success).toBe(false);
  });

  // The union schemas never run above — every fixture anchor is an object
  // definition — so a broken union (a discriminated union on the wrong key
  // throws at parse time) would pass the whole suite. Every valid fixture of
  // a union member also parses against the union it belongs to.
  const unions = model.definitions.filter(
    (definition) => definition.kind === "union",
  );
  const unionCases: Array<[string, string, string]> = unions.flatMap((union) =>
    union.kind === "union"
      ? collect("valid")
          .filter(([, anchor]) => union.members.includes(anchor))
          .map(
            ([name, , path]) =>
              [`${name} against ${union.name}Schema`, union.name, path] as [
                string,
                string,
                string,
              ],
          )
      : [],
  );

  it("has union member fixtures to run", () => {
    expect(unionCases.length).toBeGreaterThan(0);
  });

  it.each(unionCases)("%s parses", (_name, unionName, path) => {
    const validator = schemas[`${unionName}Schema`];
    const document = JSON.parse(readFileSync(path, "utf8")) as unknown;
    expect(validator.safeParse(document).success).toBe(true);
  });

  it("rejects a document that is not an event, through the union", () => {
    expect(
      schemas.EventSchema.safeParse({ type: "NOT_AN_EVENT" }).success,
    ).toBe(false);
  });

  // The tolerant layer's whole promise is that unknown keys SURVIVE the parse
  // — the strip-and-warn middleware needs to see them, and a re-serialising
  // intermediary must not lose them. A silent switch from looseObject to a
  // stripping z.object would pass every assertion above; this is what fails.
  const objectAnchors = new Set(
    model.definitions
      .filter((definition) => definition.kind === "object")
      .map((definition) => definition.name),
  );
  const probeable = collect("valid").filter(([, anchor]) =>
    objectAnchors.has(anchor),
  );

  it.each(probeable)(
    "%s keeps an unknown key through the parse",
    (_name, anchor, path) => {
      const validator = schemas[`${anchor}Schema`] as {
        safeParse: (value: unknown) => {
          success: boolean;
          data?: Record<string, unknown>;
        };
      };
      const document = JSON.parse(readFileSync(path, "utf8")) as Record<
        string,
        unknown
      >;
      const result = validator.safeParse({ ...document, xPassthroughProbe: 1 });
      expect(result.success).toBe(true);
      expect(result.data?.xPassthroughProbe).toBe(1);
    },
  );
});
